### ISSUE TITLE
I got an error when I execute "build-rest-doc" with yii console

### ISSUE THREAD

**Issue by vemaxlee** [pahanini/yii2-rest-doc#15]
`$ ./yii build-rest-doc/run
Exception 'yii\base\InvalidCallException' with message 'Setting read-only property: yii\console\Application::view'

Stack trace:
#0 /home/v/sites/yii2adv/vendor/yiisoft/yii2/BaseYii.php(521): yii\base\Component->__set('view', Array)
#1 /home/v/sites/yii2adv/vendor/yiisoft/yii2/base/Object.php(105): yii\BaseYii::configure(Object(yii\console\Application), Array)
#2 /home/v/sites/yii2adv/vendor/yiisoft/yii2/base/Application.php(206): yii\base\Object->__construct(Array)
#3 /home/v/sites/yii2adv/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#4 /home/v/sites/yii2adv/yii(26): yii\console\Application->__construct(Array)
#5 {main}

I've already set up twig and installed slate like #8 said. Can you help me to analyze the problem where it is？thank you @pahanini

**Comment by vemaxlee** [comment]
This problem has been solved, I refer to the official TWIG note, the "view" block should be placed inside the components:
[
    'components' => [
        'view' => [
            'class' => 'yii\web\View',
            'renderers' => [
                'twig' => [
                    'class' => 'yii\twig\ViewRenderer',
                    'cachePath' => '@runtime/Twig/cache',
                    // Array of twig options:
                    'options' => [
                        'auto_reload' => true,
                    ],
                    'globals' => ['html' => '\yii\helpers\Html'],
                    'uses' => ['yii\bootstrap'],
                ],
                // ...
            ],
        ],
    ],
]
